name: Update gist with WakaTime stats

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  
  push:
    branches: [ master ]

jobs:
  build:
    name: Update-gist
    runs-on: ubuntu-latest
    env:
      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GIST_BARSTYLE: SOLIDLT
      GIST_BARLENGTH: -1
      GIST_TIMESTYLE: SHORT
      UPDATE_OPTION: MARKDOWN
      MARKDOWN_FILE: ./README.md
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.14
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Update-gist
        run: go run ./cmd/box/main.go
